name: modules
favicon: null
layout_spectrum: 0.50339
typography_spectrum: 0.21939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1875
  lightness: 0.11228747083805501
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
content: []
title: DS-X.org
description: ''
github: true
